version: '3.8'

services:
  webserver:
    container_name: webserver-pmd
    build: ./php
    ports:
      - 6080:80
    volumes:
      - ./src:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
  mysql:
      container_name: mysql-pmd
      build: ./mysql
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "13306:3306"
      volumes:
        - ./data:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=mypass
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_ROOT_HOST=%
